set -e

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE SCHEMA IF NOT EXISTS auth_ms AUTHORIZATION $POSTGRES_USER;
    CREATE SCHEMA IF NOT EXISTS user_ms AUTHORIZATION $POSTGRES_USER;
EOSQL